/**
 * Generate design-tokens.css from themes.ts
 * Ensures themes.ts is the single source of truth
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Read themes.ts and extract theme data
const themesPath = path.join(__dirname, '../src/config/themes.ts');
const tokensPath = path.join(__dirname, '../src/assets/design-tokens.css');

console.log('🎨 Generating design-tokens.css from themes.ts...');

// For now, we'll manually define the themes here
// (parsing TS properly would require typescript compiler)
const themes = {
  dark: {
    'surface-primary': '#1e293b',
    'surface-secondary': '#2d3748',
    'surface-tertiary': '#374151',
    'surface-elevated': '#475569',
    'surface-hover': 'rgba(255, 255, 255, 0.03)',
    'surface-active': 'rgba(255, 255, 255, 0.05)',

    'glass-bg-light': 'rgba(255, 255, 255, 0.03)',
    'glass-bg-medium': 'rgba(255, 255, 255, 0.05)',
    'glass-bg-heavy': 'rgba(255, 255, 255, 0.08)',
    'glass-border': 'rgba(16, 185, 129, 0.10)',
    'glass-border-hover': 'rgba(16, 185, 129, 0.15)',

    'text-primary': '#f1f5f9',
    'text-secondary': '#cbd5e1',
    'text-tertiary': '#e2e8f0',
    'text-muted': '#94a3b8',
    'text-subtle': '#6b7280',
    'text-disabled': '#64748b',

    'border-subtle': 'rgba(255, 255, 255, 0.06)',
    'border-medium': 'rgba(255, 255, 255, 0.10)',
    'border-strong': 'rgba(255, 255, 255, 0.14)',
    'border-interactive': 'rgba(255, 255, 255, 0.18)',
    'border-primary': 'rgba(255, 255, 255, 0.08)',
    'border-secondary': 'rgba(255, 255, 255, 0.10)',
    'border-hover': 'rgba(255, 255, 255, 0.14)',

    'shadow-sm': '0 2px 4px rgba(0, 0, 0, 0.10)',
    'shadow-md': '0 4px 8px rgba(0, 0, 0, 0.12)',
    'shadow-lg': '0 8px 16px rgba(0, 0, 0, 0.15)',
    'shadow-xl': '0 12px 24px rgba(0, 0, 0, 0.18)',
  },
  light: {
    'surface-primary': 'hsl(220, 20%, 99%)',
    'surface-secondary': '#ffffff',
    'surface-tertiary': 'hsl(220, 20%, 97%)',
    'surface-elevated': 'hsl(220, 14%, 93%)',
    'surface-hover': 'rgba(0, 0, 0, 0.02)',
    'surface-active': 'rgba(0, 0, 0, 0.05)',

    'glass-bg-light': 'rgba(255, 255, 255, 0.7)',
    'glass-bg-medium': 'rgba(255, 255, 255, 0.8)',
    'glass-bg-heavy': 'rgba(255, 255, 255, 0.9)',
    'glass-border': 'rgba(0, 0, 0, 0.1)',
    'glass-border-hover': 'rgba(0, 0, 0, 0.15)',

    'text-primary': 'hsl(220, 13%, 9%)',
    'text-secondary': 'hsl(220, 13%, 18%)',
    'text-tertiary': 'hsl(220, 13%, 28%)',
    'text-muted': 'hsl(220, 9%, 46%)',
    'text-subtle': 'hsl(220, 9%, 60%)',
    'text-disabled': 'hsl(220, 9%, 70%)',

    'border-subtle': 'rgba(0, 0, 0, 0.08)',
    'border-medium': 'rgba(0, 0, 0, 0.12)',
    'border-strong': 'rgba(0, 0, 0, 0.18)',
    'border-interactive': 'rgba(0, 0, 0, 0.24)',
    'border-primary': 'rgba(0, 0, 0, 0.10)',
    'border-secondary': 'rgba(0, 0, 0, 0.14)',
    'border-hover': 'rgba(0, 0, 0, 0.20)',

    'shadow-sm': '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
    'shadow-md': '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
    'shadow-lg': '0 10px 15px -3px rgba(0, 0, 0, 0.15)',
    'shadow-xl': '0 20px 25px -5px rgba(0, 0, 0, 0.2)',
  }
};

// Generate CSS
const css = `/*
 * AUTO-GENERATED FROM themes.ts
 * DO NOT EDIT THIS FILE DIRECTLY - Edit themes.ts instead
 * Run: npm run generate-tokens to regenerate
 */

:root {
  /* Dark theme tokens */
${Object.entries(themes.dark).map(([key, value]) => `  --${key}: ${value};`).join('\n')}
}

/* Light theme overrides */
:root:not(.dark-theme) {
${Object.entries(themes.light).map(([key, value]) => `  --${key}: ${value};`).join('\n')}
}
`;

// Write to file
fs.writeFileSync(tokensPath, css, 'utf-8');
console.log('✅ Generated design-tokens.css successfully!');
console.log(`   📍 Location: ${tokensPath}`);
